CUDA_VISIBLE_DEVICES=6 python main.py \
	--root_path ~/ \
	--video_path ~/EHWDataset/ \
	--result_path results \
	--dataset ehwgesture \
	--n_classes 11 \
	--model phinet3d \
	--groups 3 \
	--width_mult 0.5 \
	--train_crop random \
	--learning_rate 0.01 \
	--sample_duration 12 \
	--downsample 2 \
	--batch_size 16 \
	--n_threads 32 \
	--checkpoint 1 \
	--n_val_samples 1 \
	--ehw_cam "sub2,sub2,master,master" \
	--ehw_input "depth,rgb,depth,rgb" \
	--n_epochs 250 \
	--pretrain_epochs 0